#ifndef ADDARTIST_H
#define ADDARTIST_H

#include <QWidget>
#include <QLineEdit>
#include "database.h"

namespace Ui {
class AddArtist;
}

/**
 * @brief The AddArtist class represents a widget/window for adding new artists to a database.
 * @author Binhang Zhu
 */

class AddArtist : public QWidget
{
    Q_OBJECT

public:
    /**
     * @brief Constructor for the AddArtist class.
     * @param parent The parent widget.
     */
    explicit AddArtist(QWidget *parent = nullptr);

    /**
     * @brief Destructor for the AddArtist class.
     */
    ~AddArtist();

private slots:
    /**
     * @brief Slot called when the back button is clicked.
     *        Returns to upload song menu.
     */
    void on_pushButton_clicked();

    /**
     * @brief Slot called when a add button is clicked.
     *        Attempts to add artist to database.
     */
    void on_pushButton_2_clicked();

private:
    /**
     * @brief Pointer to a Ui::AddArtist ui object, generated by Qt Designer.
     */
    Ui::AddArtist *ui;

    /**
     * @brief A line edit field for entering the artist's name.
     */
    QLineEdit *lineEdit_artistName;

    /**
      * @brief A pointer to a Database object, used for interacting with the database.
      */
    Database *d;
};

#endif // ADDARTIST_H
